/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentAssignmentIdRouteImport } from './routes/student/assignment.$id'
import { Route as TeacherStudentsStudentIdRouteImport } from './routes/teacher/students.$studentId'
import { Route as TeacherWorksheetsIdRouteImport } from './routes/teacher/worksheets.$id'
import { Route as TeacherWorksheetsNewRouteImport } from './routes/teacher/worksheets.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentIdRoute = StudentAssignmentIdRouteImport.update({
  id: '/student/assignment/$id',
  path: '/student/assignment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/teacher/students/$studentId',
    path: '/teacher/students/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherWorksheetsIdRoute = TeacherWorksheetsIdRouteImport.update({
  id: '/teacher/worksheets/$id',
  path: '/teacher/worksheets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherWorksheetsNewRoute = TeacherWorksheetsNewRouteImport.update({
  id: '/teacher/worksheets/new',
  path: '/teacher/worksheets/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/assignment/$id': typeof StudentAssignmentIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/worksheets/$id': typeof TeacherWorksheetsIdRoute
  '/teacher/worksheets/new': typeof TeacherWorksheetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/assignment/$id': typeof StudentAssignmentIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/worksheets/$id': typeof TeacherWorksheetsIdRoute
  '/teacher/worksheets/new': typeof TeacherWorksheetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/assignment/$id': typeof StudentAssignmentIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/worksheets/$id': typeof TeacherWorksheetsIdRoute
  '/teacher/worksheets/new': typeof TeacherWorksheetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/student/'
    | '/teacher/'
    | '/student/assignment/$id'
    | '/teacher/students/$studentId'
    | '/teacher/worksheets/$id'
    | '/teacher/worksheets/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/student'
    | '/teacher'
    | '/student/assignment/$id'
    | '/teacher/students/$studentId'
    | '/teacher/worksheets/$id'
    | '/teacher/worksheets/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/student/'
    | '/teacher/'
    | '/student/assignment/$id'
    | '/teacher/students/$studentId'
    | '/teacher/worksheets/$id'
    | '/teacher/worksheets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  StudentAssignmentIdRoute: typeof StudentAssignmentIdRoute
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherWorksheetsIdRoute: typeof TeacherWorksheetsIdRoute
  TeacherWorksheetsNewRoute: typeof TeacherWorksheetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignment/$id': {
      id: '/student/assignment/$id'
      path: '/student/assignment/$id'
      fullPath: '/student/assignment/$id'
      preLoaderRoute: typeof StudentAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students/$studentId': {
      id: '/teacher/students/$studentId'
      path: '/teacher/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/worksheets/$id': {
      id: '/teacher/worksheets/$id'
      path: '/teacher/worksheets/$id'
      fullPath: '/teacher/worksheets/$id'
      preLoaderRoute: typeof TeacherWorksheetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/worksheets/new': {
      id: '/teacher/worksheets/new'
      path: '/teacher/worksheets/new'
      fullPath: '/teacher/worksheets/new'
      preLoaderRoute: typeof TeacherWorksheetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  StudentAssignmentIdRoute: StudentAssignmentIdRoute,
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherWorksheetsIdRoute: TeacherWorksheetsIdRoute,
  TeacherWorksheetsNewRoute: TeacherWorksheetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
